// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQHmmd2Ml3rVDJJ-mMFra1nUsf7Uoe53Q',
    appId: '1:420333560450:web:2474678fbdb864a5d8ca9b',
    messagingSenderId: '420333560450',
    projectId: 'fir-tutorial-c009f',
    authDomain: 'fir-tutorial-c009f.firebaseapp.com',
    storageBucket: 'fir-tutorial-c009f.appspot.com',
    measurementId: 'G-CY7J9ZRT9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN-n8jXmm1WLRCfbl9XWs3XN61BgtaxTk',
    appId: '1:420333560450:android:72379e34487193bdd8ca9b',
    messagingSenderId: '420333560450',
    projectId: 'fir-tutorial-c009f',
    storageBucket: 'fir-tutorial-c009f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIL3z4-CI71rx0-R4hZ2vuE1mZT9Ow64c',
    appId: '1:420333560450:ios:4979c512b5583518d8ca9b',
    messagingSenderId: '420333560450',
    projectId: 'fir-tutorial-c009f',
    storageBucket: 'fir-tutorial-c009f.appspot.com',
    iosBundleId: 'com.example.sushiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIL3z4-CI71rx0-R4hZ2vuE1mZT9Ow64c',
    appId: '1:420333560450:ios:2a481933b25c9268d8ca9b',
    messagingSenderId: '420333560450',
    projectId: 'fir-tutorial-c009f',
    storageBucket: 'fir-tutorial-c009f.appspot.com',
    iosBundleId: 'com.example.sushiApp.RunnerTests',
  );
}
